import { renderPage } from "../renderPage.js";

renderPage({
    title: "Realist / Liberalist Analysis",
    sectionHeading: "Core Claims",
    introTxt: "../../content/realist/intro.txt",
    bodyTxt: "../../content/realist/body.txt", 
    heroImage: {
        src: "../../images/US-China.webp",
        alt: "US-China AI Image",
        title: "Generated by Google Gemini AI on September 4, 2025. All flags, maps, and likenesses contained within this image are not necessarily accurate representations of reality."
    },
    secondaryImage: {
        src: "../../images/globe.jpg",
        alt: "Globe Image",
        title: "Globe of the World"
    }
});
